export { default as LoginAsync } from 'modules/login/LoginAsync';
export { default as HomeAsync } from 'modules/home/HomeAsync';
export { default as ProductAsync } from 'modules/product/ProductAsync';
export { default as RequestAsync } from 'modules/requests/Request';
export { default as ProfileAsync } from 'modules/profile/ProfileAsync';
export { default as AccessPasswordAsync } from 'modules/accessPassword/AccessPasswordAsync';
export { default as ProductDetailAsync } from 'modules/productDetail/ProductDetailAsync';
export { default as PoliciesAsync } from 'modules/policies/Policies';
export { default as ReportsAsync } from 'modules/reports/ReportsAsync';
