export const policies = {
      labels: [],
      datasets: [
        {
          label: 'Tổng đơn',
          fill: false,
          lineTension: 0.1,
          backgroundColor: 'rgba(75,192,192,0.4)',
          borderColor: 'rgba(75,192,192,1)',
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: 'rgba(75,192,192,1)',
          pointBackgroundColor: '#fff',
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: 'rgba(75,192,192,1)',
          pointHoverBorderColor: 'rgba(220,220,220,1)',
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          borderWidth: 2,
          data: []
        },
        {
          label: 'Mới',
          fill: false,
          lineTension: 0.1,
          backgroundColor: 'rgba(83, 230, 157, 0.4)',
          borderColor: 'rgba(83, 230, 157, 1)',
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: 'rgba(83, 230, 157, 1)',
          pointBackgroundColor: '#fff',
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: 'rgba(83, 230, 157, 1)',
          pointHoverBorderColor: 'rgba(83, 230, 157,1)',
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          borderWidth: 2,
          hidden: true,
          data: []
        },
        {
          label: 'Hoàn thành',
          fill: false,
          lineTension: 0.1,
          backgroundColor: 'rgba(44, 171, 227, 0.4)',
          borderColor: 'rgba(44, 171, 227, 1)',
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: 'rgba(44, 171, 227, 1)',
          pointBackgroundColor: '#fff',
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: 'rgba(44, 171, 227, 1)',
          pointHoverBorderColor: 'rgba(44, 171, 227, 1)',
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          borderWidth: 2,
          hidden: true,
          data: []
        },
        {
          label: 'Đang đợi',
          fill: false,
          lineTension: 0.1,
          backgroundColor: 'rgba(255, 92, 51, 0.4)',
          borderColor: 'rgba(255, 92, 51, 1)',
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: 'rgba(255, 92, 51, 1)',
          pointBackgroundColor: '#fff',
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: 'rgba(255, 92, 51, 1)',
          pointHoverBorderColor: 'rgba(220,220,220,1)',
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          borderWidth: 2,
          hidden: true,
          data: []
        }
      ]
    }