export { default as HomeAsync } from './home/HomeAsync';
export { default as Error404 } from './error/Error404';
export { default as LoginPageAsync } from './account/login/LoginPageAsync';
export { default as ForgotPasswordAsync } from './account/forgotpassword/ForgotPassword';
export { default as AccessPasswordAsync } from './account/accesspassword/AccessPasswordAsync'
export { default as ProfileAsync } from './account/profile/ProfileAsync';
export { default as CategoriesAsync } from './categories/CategoriesAsync';
export { default as ProductAsync } from './product/Product';
export { default as RequestAsync } from './requests/RequestAsync';
export { default as PoliciesAsync } from './policies/PoliciesAsync';